[project]
name = "wordle"
version = "0.1.0"
description = "Python implementation of Wordle"
readme = "README.md"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
